apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-i2sa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-i2sa
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-i2sa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-i2sa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-i2sa
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-tenant/appstudio/dc-metro-map-i2sa@sha256:42293661170ff77c4014a8dd7637d5d6d55e04e992848a40c30aca07a7005d47
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
